apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards-main
data:
  dashboards.yaml: |
    apiVersion: 1
    providers:
      - name: dashboards
        type: file
        updateIntervalSeconds: 30
        options:
          path: /etc/dashboards
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
data:
  datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: 'Prometheus'
        type: prometheus
        orgId: 1
        access: proxy
        url: http://prometheus-service:8080
        is_default: true
        editable: true
        version: 1

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards-json
data:
{{ (.Files.Glob "grafana-dashboard/*").AsConfig | indent 4 }}