apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      name: grafana
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:latest
          ports:
            - name: grafana
              containerPort: 3000
          env:
            - name: GF_SERVER_HTTP_PORT
              value: "3000"
            - name: GF_AUTH_BASIC_ENABLED
              value: "false"
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: "true"
            - name: GF_AUTH_ANONYMOUS_ORG_ROLE
              value: Admin
            - name: GF_SERVER_ROOT_URL
              value: /
          volumeMounts:
            - name: datasources
              mountPath: /etc/grafana/provisioning/datasources
            # Main dashboard provisioning file directory
            - name: dashboards-main
              mountPath: /etc/grafana/provisioning/dashboards
            # Individual dashboards JSON directory
            - name: dashboards-json
              mountPath: /etc/dashboards
      volumes:
        - name: datasources
          configMap:
            name: grafana-datasources
        - name: dashboards-main
          configMap:
            name: grafana-dashboards-main
        - name: dashboards-json
          configMap:
            name: grafana-dashboards-json