apiVersion: v1
kind: Service
metadata:
  name: cerebro
  labels:
    k8s-app: cerebro
    kubernetes.io/name: "Cerebro"
spec:
  type: LoadBalancer
  ports:
  - port: {{ .Values.cerebro.port }}
    protocol: TCP
    targetPort: {{ .Values.cerebro.port }}
  selector:
    k8s-app: cerebro