apiVersion: v1
kind: Service
metadata:
  name: cerebro
  labels:
    k8s-app: cerebro
    kubernetes.io/name: "Cerebro"
spec:
  type: NodePort
  ports:
  - port: 9000
    protocol: TCP
    targetPort: ui
  selector:
    k8s-app: cerebro
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cerebro-v0
  labels:
    k8s-app: cerebro
spec:
  selector:
    matchLabels:
      k8s-app: cerebro
        
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        k8s-app: cerebro
        version: v0
    spec:
      containers:
      - name: cerebro
        image:  asia.gcr.io/sphong-kuber/cerebro:0.9.1
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /
            port: 9000
          timeoutSeconds: 1
          successThreshold: 1
        env:
          - name: ELASTICSEARCH_URL
            valueFrom:
              configMapKeyRef:
                name: es-env
                key: es-client-endpoint
        ports:
        - containerPort: 9000
          name: ui
          protocol: TCP
