apiVersion: apps/v1
kind: Deployment
metadata:
  name: es-master
  labels:
    component: elasticsearch
    role: master
    master: 'true'
spec:
  replicas: 1
  selector:
    matchLabels:
      component: elasticsearch
      role: master
      master: 'true'
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        component: elasticsearch
        role: master
        master: 'true'
    spec:
      # initContainers:
      # - name: ulimit
      #   image: alpine:3.5
      #   command: ['ulimit', '-n', '65535']

      containers:
      - name: es-master
        securityContext:
          privileged: true
          capabilities:
            add:
              - IPC_LOCK

        image: asia.gcr.io/sphong-kuber/elasticsearch-base:6.8.2
        # args:
        # - /run.sh
        # - -Ees.path.conf=/elasticsearch/config
        # readinessProbe:
        #   tcpSocket:
        #     port: 9300
        #   timeoutSeconds: 1
        #   successThreshold: 3
        imagePullPolicy: Always
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CLUSTER_NAME
          valueFrom:
            configMapKeyRef:
              name: es-env
              key: es-cluster-name
        - name: NETWORK_HOST
          value: 0.0.0.0
        - name: NODE_MASTER
          value: 'true'
        - name: NODE_DATA
          value: 'false'
        - name: HTTP_ENABLE
          value: 'true'
        - name: ES_JAVA_OPTS
          valueFrom:
            configMapKeyRef:
              name: es-env
              key: es-master-java-opts
        - name: ES_CLIENT_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: es-env
              key: es-client-endpoint
        ports:
        - name: transport
          containerPort: 9300
          protocol: TCP
          
      terminationGracePeriodSeconds: 10
