apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-logging
  labels:
    component: elasticsearch
    role: master
spec:
  selector:
    component: elasticsearch
    role: master
    # role: client
  ports:
  - name: http
    port: 9200
    protocol: TCP
