apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    k8s-app: kibana
    kubernetes.io/name: "Kibana"
spec:
  type: LoadBalancer
  ports:
  - port: 5601
    protocol: TCP
    targetPort: 5601
  selector:
    k8s-app: kibana