apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
{{ include "elasticsearch.labels" . | indent 4}}
    app: kibana
spec:
  type: LoadBalancer
  ports:
  - port: 5601
    protocol: TCP
    targetPort: 5601
  selector:
    app: kibana
{{ include "elasticsearch.selectorLabels" . | indent 4}}
