apiVersion: v1
kind: ConfigMap
metadata:
  name: curator-config
  labels:
    app: curator
data:
  action_file.yml: |-
    ---
    actions:
      1:
        action: create_index
        description: Create the index as named, with the specified extra settings.
        options:
            name: myindex
            extra_settings:
                settings:
                    number_of_shards: 2
                    number_of_replicas: 1
            disable_action: True
  config.yml: |-
    ---
    # Remember, leave a key empty if there is no value.  None will be a string,
    # not a Python "NoneType"
    client:
      hosts:
        - {{ include "elasticsearch.name" . }}-client
      port: 9200
      url_prefix:
      use_ssl: False
      certificate:
      client_cert:
      client_key:
      ssl_no_validate: False
      http_auth:
      timeout: 30
      master_only: False
    logging:
      loglevel: INFO
      logfile:
      logformat: default
      blacklist: ['elasticsearch', 'urllib3']