# Default values for elasticsearch.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
curator:
  interval: "*/1 * * * *"

cerebro:
  image: 
    repository: asia.gcr.io/able-groove-288900/cerebro
    tag: 6.8.2
    pullPolicy: IfNotPresent
  username: admin
  password: 1234
  port: 9000
  replicaCount: 1


elasticsearch: 
  strategy: RollingUpdate
  image:
    repository: asia.gcr.io/able-groove-288900/elasticsearch-base
    tag: 6.8.2
    pullPolicy: IfNotPresent

  client:
    replicaCount: 1
    heapSize: "512m"
    addtionalJavaOpts: ""
  master: 
    replicaCount: 3
    heapSize: "512m"
    addtionalJavaOpts: ""
  hot:
    replicaCount: 1
    storage: 1Gi
    heapSize: "512m"
    addtionalJavaOpts: ""
  warm:
    replicaCount: 1
    storage: 1Gi
    heapSize: "512m"
    addtionalJavaOpts: ""

  clusterName: es-cluster
  persistentEnable: "true"

kibana:
  image:
    repository: asia.gcr.io/able-groove-288900/kibana
    tag: 6.8.2
    pullPolicy: IfNotPresent

cluster:
  useremail: "sphong0417@gmail.com"
  manageremail: "sphong0417@gmail.com"

elasticsearch-exporter:
  es:
    uri: http://elasticsearch-discovery:9200
    all: true
# autoscaling:
#   enabled: false
#   minReplicas: 1
#   maxReplicas: 100
#   targetCPUUtilizationPercentage: 80
#   # targetMemoryUtilizationPercentage: 80

# nodeSelector: {}

# tolerations: []

# affinity: {}
