# Default values for elasticsearch.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

cerebro:
  image: 
    repository: asia.gcr.io/sphong-kuber/cerebro
    tag: 0.9.0
    pullPolicy: IfNotPresent

  auth:
    username: admin
    password: 1234
  port: 9000
  replicaCount: 1


elasticsearch: 
  strategy: RollingUpdate
  image:
    repository: asia.gcr.io/sphong-kuber/elasticsearch-base
    tag: 6.8.2
    pullPolicy: IfNotPresent

  client:
    replicaCount: 1
    heapsize: 512m
    addtionalJavaOpts: ""
  master: 
    replicaCount: 3
    heapsize: 512m
    addtionalJavaOpts: ""
  hot:
    replicaCount: 1
    storage: 1Gi
    heapsize: 512m
    addtionalJavaOpts: ""
  warm:
    replicaCount: 1
    storage: 1Gi
    heapsize: 512m
    addtionalJavaOpts: ""

  clusterName: es-cluster
  persistent: 
    storage: 
      enable: true

nameOverride: ""
fullnameOverride: ""

cluster:
  user:
    email: ""
  manager:
    email: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
