apiVersion: v1
metadata:
  name: es-env
kind: ConfigMap
data:
  es-cluster-name: {{ .Values.elasticsearch.clusterName }}
  es-client-java-opts: {{ printf "-Xms%s -Xmx%s" .Values.elasticsearch.client.heapSize .Values.elasticsearch.client.heapSize }}
  es-master-java-opts: {{ printf "-Xms%s -Xmx%s" .Values.elasticsearch.master.heapSize .Values.elasticsearch.master.heapSize }}
  es-hot-java-opts: {{ printf "-Xms%s -Xmx%s" .Values.elasticsearch.hot.heapSize .Values.elasticsearch.hot.heapSize }}
  es-warm-java-opts: {{ printf "-Xms%s -Xmx%s" .Values.elasticsearch.warm.heapSize .Values.elasticsearch.warm.heapSize }}
  es-client-endpoint: "http://{{ include "elasticsearch.name" . }}-client:9200"
  # es-persistent-storage=true won't allow node on shutdown to relocate shards accross the cluster
  es-persistent-storage: {{ .Values.elasticsearch.persistent.storage.enable }}
