kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "elasticsearch.name" . }}-user-binding
  labels:
{{ include "elasticsearch.labels" . | indent 4}}
subjects:
  # Google Cloud user account
  - kind: User
    name: {{ .Values.cluster.useremail }}
roleRef:
  kind: Role
  name: {{ include "elasticsearch.name" . }}-user
  apiGroup: rbac.authorization.k8s.io