apiVersion: v1
kind: Service
metadata:
  name: {{ include "elasticsearch.name" . }}-data
  labels:
{{ include "elasticsearch.labels" . | indent 4}}
    app: elasticsearch-data
spec:
  selector:
{{ include "elasticsearch.selectorLabels" . | indent 4}}
    app: elasticsearch-data
  clusterIP: None
  ports:
  - name: transport
    port: 9300
    protocol: TCP
