apiVersion: v1
kind: Service
metadata:
  name: {{ include "elasticsearch.name" . }}-client
  labels:
{{ include "elasticsearch.labels" . | indent 4}}
    app: elasticsearch-client
spec:
  selector:
    app: elasticsearch-client
{{ include "elasticsearch.selectorLabels" . | indent 4}}
  type: LoadBalancer
  ports:
  - name: http
    port: 9200
    protocol: TCP
