kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: es-client
  namespace: default
rules:
- apiGroups: ["", "apps"] # "" indicates the core API group
  resources: ["pods", "statefulsets", "deployments", "services"]
  verbs: ["get", "watch", "list",]