apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es-data-warm
  labels:
    component: elasticsearch
    role: data
spec:
  replicas: 1
  serviceName: elasticsearch-data
  selector:
    matchLabels:
      component: elasticsearch
      role: data
  template:
    metadata:
      labels:
        component: elasticsearch
        role: data
    spec:
      containers:
      - name: es-data
        securityContext:
          privileged: true
          capabilities:
            add:
              - IPC_LOCK
        image: asia.gcr.io/sphong-kuber/elasticsearch-base:6.8.2
        args:
        - /run.sh
        - -Enode.attr.box_type=warm
        # readinessProbe:
        #   tcpSocket:
        #     port: 9300
        #   timeoutSeconds: 1
        #   successThreshold: 3
        imagePullPolicy: Always
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CLUSTER_NAME
          valueFrom:
            configMapKeyRef:
              name: es-env
              key: es-cluster-name
        - name: NODE_MASTER
          value: 'false'
        - name: NODE_DATA
          value: 'true'
        - name: NODE_INGEST
          value: 'true'
        - name: HTTP_ENABLE
          value: 'false'
        - name: ES_JAVA_OPTS
          valueFrom:
            configMapKeyRef:
              name: es-env
              key: es-data-java-opts
        - name: ES_CLIENT_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: es-env
              key: es-client-endpoint
        - name: ES_PERSISTENT
          valueFrom:
            configMapKeyRef:
              name: es-env
              key: es-persistent-storage
        ports:
        - name: transport
          containerPort: 9300
          protocol: TCP
        # Random hostPort to prevent multiple ES data instances on one node
        - name: dummy
          containerPort: 28651
          protocol: TCP
          hostPort: 28651
        volumeMounts:
        - name: data
          mountPath: /data
        - name: es-config
          mountPath: /elasticsearch/conf

      terminationGracePeriodSeconds: 30

      volumes:
      - name: es-config
        configMap:
          name: es-config

  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: hdd
        resources:
          requests:
            storage: 1Gi