kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-reader-binding
  namespace: default
subjects:
  # Google Cloud user account
  - kind: User
    name: manager@gmail.com
roleRef:
  kind: Role
  name: es-manager
  apiGroup: rbac.authorization.k8s.io