{
 "title": "Kubernetes Cluster Monitoring",
 "description": "Monitors Kubernetes deployments in cluster using Prometheus. Shows overall cluster CPU / Memory of deployments, replicas in each deployment. Uses Kube state metrics and cAdvisor metrics (741)",
 "tags": [ "kubernetes" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Deployment", "query": "label_values(deployment)" },
   { "name": "Statefulset", "query": "label_values(statefulset)" },
   { "name": "Daemonset", "query": "label_values(daemonset)" },
   {
    "name": "Node",
    "query": "label_values(kubernetes_io_hostname)"
   }
  ]
 },
 "panels": [
  {
   "title": "Deployment memory usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{pod=~\"^elasticsearch.*\", kubernetes_io_hostname=~\"^$Node$\"}) / sum (kube_node_status_allocatable{node=~\"^$Node.*$\", resource=\"memory\",unit=\"byte\"}) * 100"
    }
   ]
  },
  {
   "title": "Deployment CPU usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{pod=~\"^elasticsearch.*\", kubernetes_io_hostname=~\"^$Node$\"}[2m])) / sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Waiting",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(kube_pod_container_status_waiting{pod=~\"^elasticsearch.*\"}) or vector(0))"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{pod=~\"^elasticsearch.*\", kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 5 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (kube_node_status_allocatable{node=~\"^$Node.*$\", resource=\"memory\", unit=\"byte\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{pod=~\"^elasticsearch.*\", kubernetes_io_hostname=~\"^$Node$\"}[1m]))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{kubernetes_io_hostname=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Ready (cluster)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_ready{pod=~\"^elasticsearch.*\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Running (cluster)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{pod=~\"^elasticsearch.*\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",pod=~\"^elasticsearch.*\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (pod,kubernetes_io_hostname)",
     "legendFormat": "real: {{ pod }} | {{ kubernetes_io_hostname }}"
    },
    {
     "expr": "sum (kube_pod_container_resource_requests_cpu_cores{pod=~\"^elasticsearch.*\",node=~\"^$Node$\"}) by (pod,node)",
     "legendFormat": "request:  {{ pod }} | {{ node }}"
    },
    {
     "expr": "sum (kube_node_status_allocatable{node=~\"^$Node$\",resource=\"cpu\",unit=\"core\"}) by (node)",
     "legendFormat": "available: {{ node }}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{pod=~\"^elasticsearch.*\",kubernetes_io_hostname=~\"^$Node$\"}) by (pod,kubernetes_io_hostname)",
     "legendFormat": "real: {{ pod }} | {{kubernetes_io_hostname }}"
    },
    {
     "expr": "sum ((kube_node_status_allocatable{node=~\"^$Node$\",resource=\"memory\",unit=\"byte\"})) by (node)",
     "legendFormat": "avlbl: {{ node }}"
    }
   ]
  },
  {
   "title": "All processes network I/O",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{id!=\"/\",pod=~\"^elasticsearch.*\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (pod, kubernetes_io_hostname)",
     "legendFormat": "-> {{ pod}}"
    },
    {
     "expr": "sum( rate (container_network_transmit_bytes_total{id!=\"/\",pod=~\"^elasticsearch.*\",kubernetes_io_hostname=~\"^$Node$\"}[1m])) by (pod, kubernetes_io_hostname)",
     "legendFormat": "<- {{pod }}"
    }
   ]
  }
 ]
}